### ISSUE TITLE
Empty r object - Usage

### ISSUE THREAD

**Issue by chris-english** [r-gris/tabularaster#11]
Micheal,

In the  Usage section you cite the r object can be empty (a container, no more no less), and that this is both powerful and under-utilized in raster-geometry operations. I was wondering if you could expand on this to both reveal the utility (I'm thinking testing and things of the sort), and power. I think, amid the plethora of documentation available, that sometimes the stepping back and conceptualizing the problem, hence work flow, suffers from the detail, but might also explain the sense you have of under-utilization. A cogent explanation and example of a powerful approach not frequently seen in the wild I would find interesting.

Currently wrapping my head around fmri data as my wife now uses those machines daily and see the need to get my raster skills back up. I'm looking forward to working with tabularaster (which of course the name points directly to what you allude to in Usage).  I don't know, but it might also help with conceptualizing the API.

Glad to see you're writing code like mad.
Chris

**Comment by mdsumner** [comment]
Thanks, I will do. Appreciate the feedback!

**Comment by mdsumner** [comment]
I made a start here: https://github.com/hypertidy/tabularaster/blob/master/vignettes/abstraction-illustration/raster-abstraction.Rmd

It's all setting up so far, but I think it's a worthy story to tell. It will culminate in a summary of the limits I've learned about with raster, and why I'm working on tidync. :)

**Comment by mdsumner** [comment]
And why we need a more generic set of "discretized space" data tools and transforms for rectilinear and curvlinear spaces, in addition to the standard affine transform, and the ability to get out of the plane.   It's actually been really helpful to step back and start to tell this story this way.
