### ISSUE TITLE
Functions to transform rasters to stuff plottable with ggplot

### ISSUE THREAD

**Issue by adrfantini** [r-gris/tabularaster#16]
I feel like `tabularaster` might be the right place to implement functions to facilitate plotting `raster` data with ggplot. I currently mostly use the following two functions (see below) to transform `raster` data to `data.frame` and `sf`, which can then be plotted.

Note that the current implementation of `tabularaster::as_tibble()` is almost there, but not being able to return `x` and `y` data in a single call is quite annoying.

Note that this is VERY amateurish, but you get the idea.

```
raster2df <- function(r, ..., bins=NULL, binlabels="auto", datanames=NULL, na.rm=FALSE) {
#transform rasters (stacks or layers or even just filenames) in a format easily plottable with ggplot2 (simple dataframes).
#You can provide filenames and even specify varname=.
#Does not work when providing both character strings and Raster* objects at the same time
#Optionally you can provide bins and binlabels so that you can do discrete values plotting
#Set bins to NULL to have standard cut-factors
#Set binlabels to "auto" to get something that plays nicely with ggplot

    rasters <- unstack(stack(r, ...)) #create a list of all inputs
    if (!is.null(datanames) && length(datanames) != length(rasters)) stop("Number of datanames and number of RasterLayers provided do not match!")
    if (is.null(datanames)) datanames <- unlist(lapply(rasters, names))
    asdf <- function(rlayer) {
        out <- as.data.frame(rlayer, xy=TRUE, na.rm=na.rm)
        colnames(out) <- c("x", "y", "value")
        out
    }
    if (length(rasters) > 1) { #If more than 1 input
        require(dplyr)
        dfr <- bind_rows(lapply(rasters, asdf), .id="raster") #Turn rasters into dataframe
    } else { #If just 1 input
        dfr <- cbind(datanames, as.data.frame(r, xy=TRUE, na.rm=na.rm))
    }
    colnames(dfr) <- c("raster", "x", "y", "val")
    if (!is.null(bins)) { #Cut data into bins
        bins <- unique(c(-Inf, bins, Inf)) #Check bins
        if (!is.null(binlabels)) if (binlabels=="auto") {
            binlabels <- labelsFromBins(bins)
        }
        dfr[,5] <- cut(dfr[,4], bins, labels=binlabels)
        colnames(dfr)[5] <- "factorval"
    }
    dfr$raster <- factor(as.numeric(dfr$raster), labels=datanames) #assign labels to datanames
    return(dfr)
}
```
```
labelsFromBins <- function(bins) {#Bins to labels, specifically nice for ggplot
    bins <- unique(c(-Inf, bins, Inf)) #Check bins
    labels <- c(bins[-length(bins)][-1], "")
    return(labels)
}
```
```
raster2sf <- function(r, ..., bins=NULL, binlabels="auto", datanames=NULL) {
#transform rasters (stacks or layers or even just filenames) in a format easily plottable with ggplot2 (SimpleFeatures).
#You can provide filenames and even specify varname=.
#Does not work when providing both character strings and Raster* objects at the same time
#Optionally you can provide bins and binlabels so that you can do discrete values plotting
#Set bins to NULL to have standard cut-factors
#Set binlabels to "auto" to get something that plays nicely with ggplot
    require(sf)

    rasters <- unstack(stack(r, ...)) #create a list of all inputs
    if (!is.null(datanames)) { #set the correct names
        for (i in 1:length(rasters)) {
            names(rasters[[i]]) <- datanames[i]
        }
    }
    assf <- function(x) {
        name <- names(x)
        x <- as(rasterToPolygons(x), "sf")
        names(x) <- c("val", "geometry")
        x$Dataset <- name
        x
    }
    polys_sf <- do.call(rbind, lapply(rasters, assf))
    if (!is.null(bins)) { #Cut data into bins
        if (!is.null(binlabels)) if (binlabels=="auto") {
            binlabels <- labelsFromBins(bins)
        }
        polys_sf$factorval <- cut(polys_sf$val, bins, labels=binlabels)
    }
    return(polys_sf)
}
```

**Comment by mdsumner** [comment]
as_tibble has an xy argument to add the coordinates - it's not on by default because this came from a more abstract set of workflows, you can as.data.frame(r, xy = TRUE) to get that anyway with just raster, though. 

spex::polygonize is much faster than rasterToPolygons for explicit pixel to polygon conversion. 

I haven't looked at your functions carefully, but I'm happy to - just you might find using those is enough. 

I absolutely agree there's a need for better support in ggplot2 for this, personally I'd like an abstract column that just knew it was gridded in xy - it might be a time series, or any other kind of grouping - I've experimented with that in gridcol and elsewhere but I've failed to generate any interest in the topic I'm afraid. I'm happy to explore what you're wanting to do though, I've learnt quite a lot with grid and ggplot2 recently. Thanks!

**Comment by adrfantini** [comment]
Oh, my bad, using `tabularaster` from CRAN I did not have `xy=` in the documentation. You can see my `raster2df` makes use of as.data.frame(..., xy=TRUE), with additional stuff to take care of layer naming, binning of data for categorical plots etc.

I did not know about `spex::polygonize`, that's awesome, thanks.

Yeah, I find it really neat how `ggplot` plots `sf` objects and, I expect in the future, will plot `stars` objects.
Something like that for rasters right now would be awesome. I mean, it's not a problem to transform data to dataframe and then plot but... it's just not as nice (and if you want to use projected coordinates you have to transform to `sf` and plot polygonal cells, which is slow).

**Comment by mdsumner** [comment]
It's kind of incorrect to think that a raster has to be simple features to be reprojected, there's a clear need for "mesh" raster/polygons - I've shown how to do this here but it's very much DIY it doesn't fit any existing data model as far as I can see. 

http://rpubs.com/cyclemumner/299631

There's no need to explicitly have every pixel coordinate expanded out - ultimately that happens in the graphics hardware but neither ggplot2 or many spatial R packages deal with relational data like this. (The simple features standard explicitly precludes any relational structures, which makes it a non-starter for future work here).

Appreciate your feedback!

**Comment by adrfantini** [comment]
I'm not sure I'm qualified enough to have a serious conversation on this topic but yes, in general there's no reason why ggplot or other graphical packages shouldn't be able to handle projected coordinates for raster data transparently. It looks to me that `stars` objects are handled well enough by ggplot, so I expect that `stars` will also include ggplot methods. Do you think this would be ideal, or do you see problems with this?
I'm not sure I understand the matter fully to be honest, e.g. I have no idea what you are talking about with "relational structures", would you be able to expand on that? Thanks, much appreciated.

**Comment by mdsumner** [comment]
Sorry I left this hanging, all the discussion and work is in hypertidy/silicate and hypertidy/anglr, but silicate will benefit massively from a simplification in the (temporary) hypertidy/silicore. I'm just not sure what form it will take yet.   

Is there anything this package doesn't do that your functions enabled? It's a bit incomplete, but master now is faster for sf lines and polygons thanks to spatstat and fasterize. 

Relational structures just means "not just one big table" - to remove redundancy we need multiple tables, a simple case is how fortify gave the coordinates and the groupings, but did not copy all feature data down - there's really three tables there, the coordinates, the groupings, the features. But how best to normalize (create relations across multiple tables) does depend a bit. If we want topology, or 3D plots, we need vertex normalization, the unique coordinates and the table that refers to their instances in multiple features. silicate and anglr is where I'm figuring out the workflows, and it's getting close to reasonable, I think. 

sf is partly relational, it takes the parts and separates them structurally, so there's multiple "tables", but doesn't have any storage of what relates to what, if a vertex is shared by neighbours we have to scan them all and compare to find that out. The relation of a polygon ring to a feature is stored structurally, explicitly by nested lists, plus metadata on those objects. A relational version just has all coordinates in one table, and indexes them by labels, or position.

**Comment by adrfantini** [comment]
> Is there anything this package doesn't do that your functions enabled?

Only stuff that is of high relevance to me and likely very low relevance to most people, like binning (which anyway can be easily done afterwards). However one thing of `as_tibble()` is that it relies on raster's very limited understanding of times (or names), I have never been comfortable with using that feature of raster as I've found it to be pretty limited. Also, the dimension names (`raster::names()`) could be available in an optional column, just like the dimension index.

In all honesty tho I'm not sure it's worth throwing much development effort into adding more features to `raster`; I expect that in the coming years `stars` will be getting more traction, eventually replacing `raster` in the long term.

**Comment by mdsumner** [comment]
Maybe, they are very different in style and approach. Neither work from small, independent modules and that is what I really need.

You mean point binning? That's very straightforward with cellFromXY and using the cells downstream for grouping, filtering, aggregation etc. Doing that on cell index is partly why tabularaster exists but maybe I need to make that more obvious.

Raster names I will look at, thanks!

**Comment by mdsumner** [comment]
I still hold hope for this basic pattern, but haven't tried it for ages: 

```R
ggplot(raster)  + ## no coordinate expansion! just carry the extent/dims
  geom_raster() # voila, by the magic of programming the extent/dims translated for rasterImage()

```

**Comment by adrfantini** [comment]
```R
> ggplot(raster(volcano)) + geom_raster()
Error in obj_desc(x) : object 'x' not found
```
