### ISSUE TITLE
Error in lapply(a, mat2d_f) : object 'a' not found

### ISSUE THREAD

**Issue by nasiphintshanga** [r-gris/tabularaster#20]
Hi 

I am trying to extract cell values from a raster using another a matrix created from a smaller extent of the same raster, and I get this error message.

Please help.

Regards,

**Comment by mdsumner** [comment]
Not sure, can you try installing from GitHub to make sure it's not an old bug?

Otherwise, I will need a reprex I think.

**Comment by mdsumner** [comment]
I think you've tried `cellnumbers(raster1, raster2)` which is not supported, thanks for the report. 

You could use `cellnumbers(raster1, as(extent(raster2), "SpatialPolygons"))` instead.
